development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pinterested_db_development
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pinterested_db_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pinterested_db_production
  pool: 5
  username: rails_user
  password: mint06 